function par_normfuncs(subpar)
% function par_normfuncs(subpar)
% normalize functionals
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% jbh 7/23/08
% BK: edited 4/14/10

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end


fprintf('---Normalizing funcs for Subject %d---\n',par.subnum);

graywrimg = par.graywrimg;  % BK: this will be the segmented gray image
grwrflags = par.grwrflags;
[grpth,grnm] = fileparts(graywrimg);
grmatname        = fullfile(grpth,[grnm '_sn.mat']);
allscanfiles = par.allurscanfiles; %AC Change to allurscanfiles
spm_write_sn(allscanfiles, grmatname,grwrflags); %AC Change to allurscanfiles

fprintf('---Normalizing funcs COMPLETED for Subject %d---\n',par.subnum);


cd(origdir);