function par_realign(subpar)
% function par_realign(subpar)
% runs realignment
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% modified from old parscripts by jbh on 7/23/08


origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end

% run realign; generate mean img
fprintf('---Realign for %s---\n',par.substr);
realflag = par.realflag;
reslflag = par.reslflag;

if par.aligntosynthepi == 1
    Porig = par.scanfiles;
    P = cell(1,par.numscans+1);
     for x = 1:length(Porig) %go through the entire cell array and move each scan/session over one cell so that we can insert the synthEPI as the first session/scan
         P{x+1} = Porig{x};
     end
     P{1} = par.synthEPI; %put the synthEPI as first session 
else  
P = par.scanfiles; %AC Change - no longer ascanfiles because we are not doing slicetiming 
end
spm_realign(P, realflag);
spm_reslice(P, reslflag);

%save ps
par_print(par);

cd(origdir);
fprintf('---Realign COMPLETED for %s---\n',par.substr);