function par_coregwrapper(subpar)
% function par_coregwrapper(subpar)
% if a synthetic EPI was created then coregisters the hires to the cal_rho (which is already in the same space as the synthetic EPI) and if there is no synthetic EPI then
% the script registers the mean func to the hires
%
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end

synthEPI = par.synthEPI; %AC Change

if exist(synthEPI)  %AC Change check to see if a synthetic EPI was created
    fprintf('---Synthetic EPI found for %s---\n',par.substr);
    coregtype = 1;
else
     fprintf('---Synthetic EPI not found for %s---\n',par.substr);
     coregtype = 2;
     pause(5); % built-in bailout time for if you wanted to coregister to synthEPI 
end
    
if coregtype == 1;
    % coreg HiRes to cal_rho
    fprintf('---Coreg hi-res to cal_rho for Subject %s---\n',par.substr);

    refimg2 = par.calrho;
    sourceimg2 = par.hiresimg;
    par_coreg(refimg2, sourceimg2);
    par_print(par); %print out ps
    fprintf('---Coreg hi-res to cal_rho COMPLETED for Subject %s---\n',par.substr);

elseif coregtype == 2;
  error('No synthetic EPI found. Aborting.');
    
end


cd(origdir);