function R = par_makeregs(subpar)
% function R = par_makeregs(subpar)
% makes motion and concat regressors...
% regs 1-6: motion
% regs 7-15: scan blocks
% 
% subpar refers to either the subject number (in string notation) or
% the par struct generated by par = par_params(subject)
% 
% jbh 7/24/08


origdir = pwd;



% ---load par params if need be---
if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end


% motion regs
cd(par.funcdir);
mr = [];
for P = 1:par.numscans 
    if par.data_seg == 1
        if P<10
            C = textscan(fopen(['scan0' num2str(P) '/rscan0' num2str(P) '.par']),'%n%n%n%n%n%n'); %AC Change since we use fsl for motion correction there is a new motion parameters file rscan0*.par
        else
            C = textscan(fopen(['scan' num2str(P) '/rscan' num2str(P) '.par']),'%n%n%n%n%n%n'); %AC Change since we use fsl for motion correction there is a new motion parameters
        end
    elseif par.data_seg ==2
         C = textscan(fopen('localizer/rlocalizer.par'),'%n%n%n%n%n%n'); %AC Change since we use fsl for motion correction there is a new motion parameters file rscan0*.par
    end
    
    for dd = 1:length(C)
        D{dd} = C{dd}(par.minvol:end); %AC Change since we do not drop the first few dead volumes from our scans when we do motion correction in fsl, we need to drop those volumes' motion parameters now
    end
    mr = vertcat(mr, cell2mat(D));
end

if par.data_seg == 1 %only have block regessor for experiment data
    % scan block regs
    totvols = sum(par.numvols);
    % on 10/29/08 brice changed the below to add "-1"
    Bl = zeros(totvols,(par.numscans-1));

    for i = 1:(par.numscans-1)
        if i~=1
            startRow = 1+(sum(par.numvols(1:i-1)));
        else
            startRow = 1;
        end
        Bl(startRow:(startRow+(par.numvols(i)-1)),i) = 1;
    end
    % add drift regs???


    % combine the two
    if length(mr) ~= length(Bl)
        error('Regressor size mismatch!');
    end
    R = horzcat(mr, Bl);
    
elseif par.data_seg ==2 %if its the localizer data
    R = mr;
end


% save regs in behavioral

cd(par.subdir);
if ~exist(par.behavdir,'dir')
    mkdir(par.behavdir);
else %back up any existing regs.mat file
    cd(par.behavdir);
    if exist([par.behavdir '/regs.mat'],'file')
        movefile('regs.mat', ['regs.mat-' date]);
    end
end
cd(par.behavdir);


save regs.mat R;

cd(origdir);
