function par_wholeshebang(subpar, flags,data_segs)
% function wholeshebang(subpar, flags)
% runs an entire subject start to finish.
%
% subpar refers to either the subject number (in string notation) or
% the par struct generated by par = par_params(subject)
%
% flags defaults to all stages, or individual stages can be chosen from:
% m = makevols
% a = make anatomicals
% s = slice timing
% l = realignment
% c = coregister inplane anat to mean func, and hires to inplane
% g = segment and normalize gray matter
% n = normalize functionals
% h = smooth functionals
% k = make specmask
% o = make and move onsets
% r = make regressors
% p = specify model
% e = run model
% t = make contrasts
%
% M = mail .ps file to yourself

for i = 1:length(data_segs)
    origdir = pwd;

if ~exist('subpar', 'var')
    error('Must specify subject!');
end

% ---load par params if need be---
if isstruct(subpar) % if it is par_params struct
    par = subpar;
end


%set up logdir if it doesn't exist (for saving par to, etc)
if ~exist(par.logdir, 'dir'); mkdir(par.logdir); end
%save par file so that you know what you did!
parfile = [par.logdir filesep ['par-' date '.mat']];
save(parfile, 'par');


% Preprocessing
if ismember('a',flags); par_qualitycheck_rois(par); end

if ismember('q',flags); par_qualitycheck_spikes(par); end

if data_segs(i) == 1 %if its the experiment
    if ismember('m',flags); par_moverawdata(par); end

    if ismember('y',flags); par_syntheticEPI(par); end
end


if ismember('l',flags); par_realign_fsl(par); end

if ismember('w',flags); par_unwarp(par); end

if ismember('z',flags); par_artifact_removal(par); end

if data_segs(i) == 1 %if its the experiment
    if ismember('c',flags); par_coregwrapper(par); end

    if ismember('g',flags); par_segnorm(par); end

end
if ismember('n',flags); par_normfuncs(par); end

if ismember('h',flags); par_smoothfuncs(par); end

if ismember('k',flags); par_makespec(par); end


% Modeling, etc
if ismember('o',flags); par_makeonsets(par); end
if ismember('r',flags); par_makeregs(par); end
if ismember('p',flags); par_mod_spec(par); end
if ismember('e',flags); par_mod_est(par); end
if ismember('t',flags); par_setcontrasts(par); end

cd(origdir);

%clean up any of those irritating .ps files in the scripts directory
delete *.ps

fprintf('\n%s done.\n', par.substr);
end
end
